### ISSUE TITLE
SEO: Add JSON-LD/schema.org to all items in the series WO 372 and PROB 11

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#11]
## Tasks
- [x] Identify the fields that will be mapped to the JSON-LD schema from WO 372
- [ ] Identify the fields that will be mapped to the JSON-LD schema from PROB 11
- [ ] Confirm with .NET designers if their time and/or input is required?
- [ ] Deplot to TEST
- [ ] Deploy to LIVE

## Supplementary tasks
- [ ] How does Google's use JSON-LD schema

## Acceptance criteria
- [ ] JSON-LD is included on all details pages within WO 372 and PROB 11 (HOW: spot checks??)
- [ ] Confirm that the data is correctly structures [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool)

## Measurement of success
- [ ] More appropriate display of content within Google search results
- [ ] Appropriate items returning within Google search results

**Comment by grange85** [comment]
Matt's proposed schema for WO 372
`{
	"@context": "http://schema.org",
	"@type": "DigitalDocument",
	"name": "Medal card of Owen, Wilfred E S Corps: Manchester Regiment Rank: Lieutenant",
	"description": "War Office: Service Medal and Award Rolls Index, First World War. Medal card",
	"temporalCoverage": "1914/1920",
	"about": {
		"@type": "Person",
		"familyName": "Owen",
		"givenName": "Wilfred E S",
		"memberOf": {
			"@type": "Organization",
			"name": "Manchester Regiment"
		}
	},
	"publisher": {
		"@type": "GovernmentOrganization",
		"url": "http://www.nationalarchives.gov.uk"
	}
}`

@netdesignr are you happy to start looking how you can get this into WO 372 items in Discovery?

**Comment by grange85** [comment]
@netdesignr I spoke to Andrew yesterday and he explained that there were some crossed-wires in that the schema could be pulled more accurately directly from the Discovery DB and that he was going to get a dev to have a look at this - it highlighted that we do need to work more closely with the back-end devs as it's likely that we will be wanting more changes to Discovery during the project. If you could maybe catch up with Samiksha and Matt H to see if there's any more work that needs to be done from our end - or if they need anything more.
