### ISSUE TITLE
Get schema into WO 372 on Discovery

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#17]
# Schema: Work with back-end devs to get schema into WO 372

## Dependencies
- Confirm title and description (see #18 )
- Back-end developer

## Tasks
- [x] Provide finalised schema pattern to back end devs
- [x] Confirm location of the schema
- [x] Extract schema content from back-end database
- [x] Place schema into the document at item level

### Proposed schema for WO 372
```
{
	"@context": "http://schema.org",
	"@type": "DigitalDocument",
	"name": "Medal card of Owen, Wilfred E S Corps: Manchester Regiment Rank: Lieutenant",
	"description": "War Office: Service Medal and Award Rolls Index, First World War. Medal card",
	"temporalCoverage": "1914/1920",
	"about": {
		"@type": "Person",
		"familyName": "Owen",
		"givenName": "Wilfred E S",
		"memberOf": {
			"@type": "Organization",
			"name": "Manchester Regiment"
		}
	},
	"publisher": {
		"@type": "GovernmentOrganization",
		"url": "http://www.nationalarchives.gov.uk"
	}
}
```

## Acceptance criteria
- All items in WO 372 have correct and appropriate schema ~ confirmed via ?? *spot-checking*?

## Measure of success
- Improved display of results in Google (and other search engines)
- Improved ranking of items in Google (and other search engines)

**Comment by netdesignr** [comment]
Done
