### ISSUE TITLE
 Schema: Work with back-end devs to get title and meta description updated in WO 372

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#19]
## Dependencies
- Confirm title and description (see #18 )
- Back-end developer

## Tasks
- [ ] Provide finalised title and description patterns to back end devs
- [ ] Extract title and description content from back-end database
- [ ] update title and descriptio into the document at item level

## Acceptance criteria
- All items in WO 372 have correct and appropriate title and description ~ confirmed via ?? *spot-checking*?

## Measure of success
- Improved display of results in Google (and other search engines)
- Improved ranking of items in Google (and other search engines)
