### ISSUE TITLE
Help: Develop application to scrape the research guides

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#20]
## Tasks
- [ ] scrape research guides and identify series, pieces, ranges and items
- [ ] output as xml
- [ ] establish how to automate update of xml

## Acceptance criteria
- well formed xml output and available to Discovery

## Measure of success
- XML output
