### ISSUE TITLE
Investigate updating Help with your research sections in Discovery with research guide links

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#22]
## Dependencies
- XML output #20 
- Integration from Discovery #21 
- Back-end developer

## Tasks
- [ ] Confirm location and design of research guide links at series level
- [ ] Confirm location and design of research guide links at item level
- [ ] Confirm location and design of research guide links at piece level
- [ ] Code!

## Acceptance criteria
- Links from Discovery back to research guides

## Measure of success
- Reduction in enquiries??
