### ISSUE TITLE
Discovery UI audit

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#46]
## Tasks
- [ ] [TNA record description](http://discovery.nationalarchives.gov.uk/details/r/C3808806)
- [ ] [TNA record description (series level)](http://discovery.nationalarchives.gov.uk/details/record?catid=12173&catln=3)
- [ ] [Records of other archives descriptions](http://discovery.nationalarchives.gov.uk/details/r/9995f842-4b16-40d5-af0a-bb204428bc28)
- [ ] [Basic Search results](http://discovery.nationalarchives.gov.uk/results/r)
- [ ] [TNA Search results](http://discovery.nationalarchives.gov.uk/results/r)
- [ ] [Discovery homepage](http://discovery.nationalarchives.gov.uk/)
- [ ] [Repository details (Archon)](http://discovery.nationalarchives.gov.uk/details/a/A13530954)
- [ ] [TNA digital record description](http://discovery.nationalarchives.gov.uk/details/r/)
- [ ] [Record creators catalogue descriptions](http://discovery.nationalarchives.gov.uk/details/c/F254188)
- [ ] [Record creators search results](http://discovery.nationalarchives.gov.uk/results/c)
- [ ] [Advanced search](http://discovery.nationalarchives.gov.uk/advanced-search)
- [ ] [Advanced search results](http://discovery.nationalarchives.gov.uk/results/r)
- [ ] [Browse by hierarchy TNA catalogue](http://discovery.nationalarchives.gov.uk/browse/r/h)
- [ ] [Browse by reference TNA catalogue](http://discovery.nationalarchives.gov.uk/browse/r/r)
- [ ] [Shopping basket](http://discovery.nationalarchives.gov.uk/basket)
- [ ] [Browse other archives](http://discovery.nationalarchives.gov.uk/browse/r/)
- [ ] [Browse home](http://discovery.nationalarchives.gov.uk/browse)
- [ ] [Find an Archive search results](http://discovery.nationalarchives.gov.uk/results/a)
- [ ] [Manor search results](http://discovery.nationalarchives.gov.uk/results/c)
- [ ] [Paid search: FOI 1939 register](http://discovery.nationalarchives.gov.uk/paidsearch/foi1939register)
- [ ] [Find an archive search](http://discovery.nationalarchives.gov.uk/find-an-archive)
- [ ] [Discovery account: Your orders](http://discovery.nationalarchives.gov.uk/account/yourorders)
- [ ] [Manor search](http://discovery.nationalarchives.gov.uk/manor-search)
- [ ] [Order copy](http://discovery.nationalarchives.gov.uk/pagecheck/start/C14124882)

## Acceptance criteria
- *Spreadsheet with all the interface elements logged on all the above pages*
