### ISSUE TITLE
Autocomplete workshop

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#82]
## Dependencies
- 

## Tasks
- [ ] book a room and time for the workshop @grange85 
- [ ] establish desired outcomes  
- [ ] establish workshop requirements (post-its, pens etc.) @jklepfer 
- [ ] pre-workshop research on existing use of autocomplete (_whole team_)

**Comment by jklepfer** [comment]
Workshop Requirements: 
pens/pencils
sharpies
post its
A3 print outs for brainstorm (Jenifer to bring these) 
whiteboard markers depending on venue :)

**Comment by jklepfer** [comment]
[auto suggestion research.docx](https://github.com/nationalarchives/findability/files/2769544/auto.suggestion.research.docx)

**Comment by grange85** [comment]
While it's not auto**suggest** - GDS does have an open proposal on autofill that may have a bearing on interface design:
https://github.com/alphagov/govuk-design-system-backlog/issues/4

**Comment by grange85** [comment]
This _draft guidance_ is linked to from the above GDS issue
https://paper.dropbox.com/doc/Type-ahead--AV2a4iQfRNmfF5QV5X7yA4k5Ag-BIMIenFtAnzbXW5mbqEWK

**Comment by hoake** [comment]
Ebay use a best match system that buyers prefer to sellers. They have a number of posts on search listings and explain what key features they use in their algoriths
https://www.ebay.com/help/selling/listings/listing-tips/optimising-listings-best-match?id=4166

**Comment by grange85** [comment]
Amazon autosuggests from the first character but has a second or so lag before the suggestion kicks in - it suggests a  category for it's primary suggestion
![image](http://www.nationalarchives.gov.uk/zzz/tmp/amazon-autosuggest.gif)

It managed me misspelling pretty well (although not all the time)
![image](https://user-images.githubusercontent.com/783875/51400273-ecb9cd00-1b3f-11e9-8d0e-66d9c2d3a89b.png)

**Comment by grange85** [comment]
@hoake do you think that the results for the misspelling are because sellers had misspelled - rather than ebay being clever (it certainly used to be a thing finding bargains when sellers misspelled things on ebay)

> So what happens when I misspell something? Well, I used "Staedtler" as my search term as this it is easy to misspell (and yes a pencil was on my desk when I was looking for inspiration). Spelling it correctly provided a large list of suggestions.
