### ISSUE TITLE
Prepare TNA searches for a search queries dashboard

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#83]
## Dependencies
- back end development (possibly)

## Tasks
- [ ] investigate using GTM to add search parameters
- [ ] Establish with developers the requirements for adding a search parameter to website search
- [ ] Establish with developers the requirements for adding a search parameter to Discovery search
- [ ] Implement the changes on TEST and LIVE

## Acceptance criteria
- searches can now be separated by search platform (Discovery or website)

## Measure of success
- search is ready to create a query term dashboard
